application: fotoprojo
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /
  script: main.py
  login: required
    
- url: /authenticate
  script: main.py
  login: required
  
- url: /logout
  script: main.py
  login: required

- url: /init
  script: main.py
  login: admin